# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'top left'), (2, 'top right'), (3, 'bottom left'), (4, 'bottom right')], verbose_name='Position in page')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='When created')),
                ('when_updated', models.DateTimeField(auto_now=True, verbose_name='When updated')),
                ('content', froala_editor.fields.FroalaField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Advertising',
                'verbose_name_plural': 'Advertising',
                'ordering': ('position', 'rank'),
            },
        ),
    ]
