# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:28
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_advertising_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'ordering': ('position', 'rank'), 'verbose_name': 'Advertising', 'verbose_name_plural': 'Advertisings'},
        ),
        migrations.AlterField(
            model_name='advertising',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
