# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_platform_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
