# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_app_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.AddField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='app',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
    ]
