# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20171025_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='when_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='When updated'),
        ),
    ]
