# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20171028_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='when_updated',
            field=models.DateTimeField(auto_now=True, help_text='Important for meta tags(seo)', verbose_name='When updated'),
        ),
    ]
