# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20171101_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, default='qka', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description_en',
            field=models.CharField(blank=True, default='qka', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description_ru',
            field=models.CharField(blank=True, default='qka', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
