# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20171101_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='developer_link',
            field=models.URLField(default='', verbose_name='Developer link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='developer_name',
            field=models.CharField(default='', max_length=50, verbose_name='Developer name'),
            preserve_default=False,
        ),
    ]
