# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMETA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('description', models.CharField(default='Description', max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='meta')),
            ],
            options={
                'verbose_name': 'Site META tags',
            },
        ),
    ]
