# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitemeta_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='author_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='author_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='description_en',
            field=models.CharField(default='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='description_ru',
            field=models.CharField(default='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='keywords_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='keywords_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='title_en',
            field=models.CharField(default='Title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='title_ru',
            field=models.CharField(default='Title', max_length=255, null=True),
        ),
    ]
